"""Add budget items

Revision ID: 81ef354f0f17
Revises: 001_initial_schema
Create Date: 2026-05-10 13:40:48.747270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81ef354f0f17'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_items_trip_id'), 'budget_items', ['trip_id'], unique=False)
    op.alter_column('activities', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_activities_city_id'), table_name='activities')
    op.drop_index(op.f('idx_activities_type'), table_name='activities')
    op.create_index(op.f('ix_activities_city_id'), 'activities', ['city_id'], unique=False)
    op.create_index(op.f('ix_activities_type'), 'activities', ['type'], unique=False)
    op.alter_column('checklist_items', 'is_packed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('checklist_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_checklist_trip_id'), table_name='checklist_items')
    op.create_index(op.f('ix_checklist_items_trip_id'), 'checklist_items', ['trip_id'], unique=False)
    op.drop_index(op.f('idx_cities_country'), table_name='cities')
    op.drop_index(op.f('idx_cities_name'), table_name='cities')
    op.create_index(op.f('ix_cities_country'), 'cities', ['country'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_notes_trip_id'), table_name='notes')
    op.create_index(op.f('ix_notes_trip_id'), 'notes', ['trip_id'], unique=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_index(op.f('idx_stop_activities_stop_id'), table_name='stop_activities')
    op.create_index(op.f('ix_stop_activities_stop_id'), 'stop_activities', ['stop_id'], unique=False)
    op.alter_column('stops', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_stops_city_id'), table_name='stops')
    op.drop_index(op.f('idx_stops_trip_id'), table_name='stops')
    op.create_index(op.f('ix_stops_city_id'), 'stops', ['city_id'], unique=False)
    op.create_index(op.f('ix_stops_trip_id'), 'stops', ['trip_id'], unique=False)
    op.alter_column('trips', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trips', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_trips_share_code'), table_name='trips')
    op.drop_index(op.f('idx_trips_user_id'), table_name='trips')
    op.drop_constraint(op.f('trips_share_code_key'), 'trips', type_='unique')
    op.create_index(op.f('ix_trips_share_code'), 'trips', ['share_code'], unique=True)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'en'::character varying"))
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_share_code'), table_name='trips')
    op.create_unique_constraint(op.f('trips_share_code_key'), 'trips', ['share_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_index(op.f('idx_trips_share_code'), 'trips', ['share_code'], unique=False)
    op.alter_column('trips', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trips', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_stops_trip_id'), table_name='stops')
    op.drop_index(op.f('ix_stops_city_id'), table_name='stops')
    op.create_index(op.f('idx_stops_trip_id'), 'stops', ['trip_id'], unique=False)
    op.create_index(op.f('idx_stops_city_id'), 'stops', ['city_id'], unique=False)
    op.alter_column('stops', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_stop_activities_stop_id'), table_name='stop_activities')
    op.create_index(op.f('idx_stop_activities_stop_id'), 'stop_activities', ['stop_id'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.create_index(op.f('idx_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notes_trip_id'), table_name='notes')
    op.create_index(op.f('idx_notes_trip_id'), 'notes', ['trip_id'], unique=False)
    op.alter_column('notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_country'), table_name='cities')
    op.create_index(op.f('idx_cities_name'), 'cities', ['name'], unique=False)
    op.create_index(op.f('idx_cities_country'), 'cities', ['country'], unique=False)
    op.drop_index(op.f('ix_checklist_items_trip_id'), table_name='checklist_items')
    op.create_index(op.f('idx_checklist_trip_id'), 'checklist_items', ['trip_id'], unique=False)
    op.alter_column('checklist_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('checklist_items', 'is_packed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_activities_type'), table_name='activities')
    op.drop_index(op.f('ix_activities_city_id'), table_name='activities')
    op.create_index(op.f('idx_activities_type'), 'activities', ['type'], unique=False)
    op.create_index(op.f('idx_activities_city_id'), 'activities', ['city_id'], unique=False)
    op.alter_column('activities', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_budget_items_trip_id'), table_name='budget_items')
    op.drop_table('budget_items')
    # ### end Alembic commands ###
